#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: ./mkconfig.sh [options]

Options:
  --profile server|kde|both   Build target profile(s). Default: both.
  --config PATH               Optional env config generated by scripts/mkconfig-tui.sh.
  --skip-smoke                Skip post-build smoke tests (not recommended).
  --dry-run                   Print actions without executing build.
  -h, --help                  Show this help.
USAGE
}

PROFILE="both"
USER_CONFIG=""
SKIP_SMOKE="false"
DRY_RUN="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="${2:-}"
      shift 2
      ;;
    --config)
      USER_CONFIG="${2:-}"
      shift 2
      ;;
    --skip-smoke)
      SKIP_SMOKE="true"
      shift
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

case "$PROFILE" in
  server|kde|both) ;;
  *)
    echo "Invalid profile: $PROFILE" >&2
    exit 1
    ;;
esac

if [[ -n "$USER_CONFIG" && ! -f "$USER_CONFIG" ]]; then
  echo "Config file not found: $USER_CONFIG" >&2
  exit 1
fi

if [[ -n "$USER_CONFIG" ]]; then
  # shellcheck disable=SC1090
  source "$USER_CONFIG"
fi

build_one() {
  local p="$1"
  local cmd=("./scripts/build-profile.sh" "--profile" "$p")
  if [[ -n "$USER_CONFIG" ]]; then
    cmd+=("--config" "$USER_CONFIG")
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] %q ' "${cmd[@]}"
    echo
    return 0
  fi

  "${cmd[@]}"
}

if [[ "$PROFILE" == "both" ]]; then
  build_one "server"
  build_one "kde"
else
  build_one "$PROFILE"
fi

if [[ "$SKIP_SMOKE" != "true" ]]; then
  smoke_cmd=(./tests/smoke/run.sh --profile "$PROFILE" --require-artifacts --with-iso-rootfs)
  if [[ "${YGG_ENABLE_QEMU_SMOKE:-false}" == "true" ]]; then
    smoke_cmd+=(--with-qemu-boot)
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    printf '[dry-run] %q ' "${smoke_cmd[@]}"
    echo
  else
    "${smoke_cmd[@]}"
  fi
fi

echo "Build workflow completed for profile: $PROFILE"
