#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH=""
INVOKE_PATH=""
REPO_ROOT="${YGGDRASIL_MAKER_REPO_ROOT:-/workspace/repo}"
EDIT_BIN_BUNDLE="/workspace/input/tools/edit"
BUILD_REPO_ROOT="/workspace/build/repo"
export YGG_FORCE_IPV4_DOWNLOADS="${YGG_FORCE_IPV4_DOWNLOADS:-true}"
export YGG_DEBOOTSTRAP_PLAIN_WGET="${YGG_DEBOOTSTRAP_PLAIN_WGET:-true}"
FORCE_IPV4_BIN_DIR=""

usage() {
  cat <<'USAGE'
Usage: maker-build-container-entrypoint.sh --config /workspace/input/ygg.local.toml --invoke /workspace/input/invocation.json
USAGE
}

json_field() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
import json
import sys

path = sys.argv[1]
key = sys.argv[2]
with open(path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)
value = payload.get(key)
if value is None:
    sys.exit(1)
if isinstance(value, bool):
    print("true" if value else "false")
else:
    print(value)
PY
}

toml_field() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
import sys
import tomllib

path = sys.argv[1]
key = sys.argv[2]
with open(path, 'rb') as handle:
    payload = tomllib.load(handle)
value = payload.get(key)
if value is None:
    sys.exit(1)
if isinstance(value, bool):
    print('true' if value else 'false')
else:
    print(value)
PY
}

emit_event() {
  local kind="$1"
  local payload_json="${2-}"
  if [[ -z "$payload_json" ]]; then
    payload_json='{}'
  fi
  python3 - "$kind" "$payload_json" <<'PY'
import json
import sys

kind = sys.argv[1]
payload = json.loads(sys.argv[2])
payload["type"] = kind
print(json.dumps(payload), flush=True)
PY
}

emit_stage_started() {
  emit_event "stage-started" "{\"stage\":\"$1\"}"
}

emit_stage_finished() {
  emit_event "stage-finished" "{\"stage\":\"$1\"}"
}

emit_failure() {
  local code="$1"
  local message_key="$2"
  local detail="$3"
  python3 - "$code" "$message_key" "$detail" <<'PY'
import json
import sys

payload = {
    "type": "failure",
    "code": sys.argv[1],
    "message_key": sys.argv[2],
    "detail": sys.argv[3],
}
print(json.dumps(payload), flush=True)
PY
}

emit_artifact_ready() {
  local profile="$1"
  local path="$2"
  python3 - "$profile" "$path" <<'PY'
import json
import sys

payload = {
    "type": "artifact-ready",
    "profile": sys.argv[1],
    "path": sys.argv[2],
}
print(json.dumps(payload), flush=True)
PY
}

emit_log_line() {
  local stream="$1"
  local line="$2"
  python3 - "$stream" "$line" <<'PY'
import json
import sys

payload = {
    "type": "log-line",
    "stream": sys.argv[1],
    "line": sys.argv[2],
}
print(json.dumps(payload), flush=True)
PY
}

log_line() {
  printf '[yggdrasil-maker-build] %s\n' "$*" >&2
}

write_static_resolver_config() {
  local target="$1"
  shift
  local servers=("$@")
  {
    printf '# Generated by yggdrasil-maker-build\n'
    printf 'options timeout:2 attempts:3 rotate\n'
    for server in "${servers[@]}"; do
      [[ -n "$server" ]] || continue
      printf 'nameserver %s\n' "$server"
    done
  } > "$target"
}

configure_builder_network() {
  local original_resolver="/etc/resolv.conf"
  local -a original_servers=()
  local -a preferred_servers=("1.1.1.1" "1.0.0.1" "8.8.8.8" "8.8.4.4")
  local -a final_servers=()

  while read -r _ server _; do
    [[ -n "${server:-}" ]] || continue
    original_servers+=("$server")
  done < <(grep -E '^nameserver[[:space:]]+' "$original_resolver" || true)

  for server in "${preferred_servers[@]}"; do
    final_servers+=("$server")
  done
  for server in "${original_servers[@]}"; do
    if [[ " ${final_servers[*]} " != *" $server "* ]]; then
      final_servers+=("$server")
    fi
  done

  if [[ ${#final_servers[@]} -eq 0 ]]; then
    final_servers=("1.1.1.1" "8.8.8.8")
  fi

  write_static_resolver_config "$original_resolver" "${final_servers[@]}"

  cat <<'EOF' > /etc/apt/apt.conf.d/99ygg-network-resilience
Acquire::Retries "10";
Acquire::http::Timeout "30";
Acquire::https::Timeout "30";
Acquire::http::Pipeline-Depth "0";
EOF

  log_line "resolver configured with: ${final_servers[*]}"
}

prepare_debootstrap_download_path() {
  local repo_root="${BUILD_REPO_ROOT:-$REPO_ROOT}"
  local partial_dir="$repo_root/chroot/var/cache/apt/archives/partial"
  if [[ -d "$partial_dir" ]]; then
    find "$partial_dir" -maxdepth 1 -type f -name '*.deb' -delete || true
  fi
}

patch_debootstrap_for_plain_wget() {
  [[ "$YGG_DEBOOTSTRAP_PLAIN_WGET" == "true" ]] || return 0
  python3 - <<'PY'
from pathlib import Path
path = Path("/usr/share/debootstrap/functions")
text = path.read_text()
old = """wgetprogress () {
\t[ ! \"$VERBOSE\" ] && NVSWITCH=\"-nv\"
\tlocal ret=0
\tif [ \"$USE_DEBIANINSTALLER_INTERACTION\" ] && [ \"$PROGRESS_NEXT\" ]; then
\t\t# The exit status of a pipeline is that of the last command in
\t\t# the pipeline, so wget's exit status must be saved in the
\t\t# pipeline's first command.  Since commands in a pipeline run in
\t\t# subshells, we have to print the exit status (on a file
\t\t# descriptor other than standard output, which is used by the
\t\t# pipeline itself) and then assign it to $ret outside of the
\t\t# pipeline.  The \"||\" is necessary due to \"set -e\"; otherwise, a
\t\t# non-zero exit status would cause the echo command to be
\t\t# skipped.  If wget succeeds, $ret will be \"\", so it then has to
\t\t# be set to a default value of 0.
\t\tret=$({ { wget -U \"debootstrap/$VERSION (debian-installer)\" \"$@\" 2>&1 >/dev/null || echo $? >&2; } | \"$PKGDETAILS\" \"WGET%\" \"$PROGRESS_NOW\" \"$PROGRESS_NEXT\" \"$PROGRESS_END\" >&3; } 2>&1)
\t\t: \"${ret:=0}\"
\telse
\t\twget -U \"debootstrap/$VERSION\" ${NVSWITCH:+\"$NVSWITCH\"} \"$@\"
\t\tret=$?
\tfi
\treturn $ret
}
"""
new = """wgetprogress () {
\t[ ! \"$VERBOSE\" ] && NVSWITCH=\"-nv\"
\twget -U \"debootstrap/$VERSION\" ${NVSWITCH:+\"$NVSWITCH\"} \"$@\"
\treturn $?
}
"""
if old in text and new not in text:
    path.write_text(text.replace(old, new))
PY
}

cleanup() {
  if [[ -n "$FORCE_IPV4_BIN_DIR" && -d "$FORCE_IPV4_BIN_DIR" ]]; then
    rm -rf "$FORCE_IPV4_BIN_DIR"
  fi
}
trap cleanup EXIT

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      CONFIG_PATH="${2:-}"
      shift 2
      ;;
    --invoke)
      INVOKE_PATH="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$CONFIG_PATH" || -z "$INVOKE_PATH" ]]; then
  usage >&2
  exit 1
fi

emit_stage_started "preflight"

if [[ ! -f "$CONFIG_PATH" ]]; then
  emit_failure "build-config-invalid" "config_missing" "config file not found: $CONFIG_PATH"
  exit 1
fi

if [[ ! -f "$INVOKE_PATH" ]]; then
  emit_failure "build-config-invalid" "invoke_missing" "invocation file not found: $INVOKE_PATH"
  exit 1
fi

if [[ ! -d "$REPO_ROOT" ]]; then
  emit_failure "unsupported-platform" "repo_root_missing" "repo root not found: $REPO_ROOT"
  exit 1
fi

profile="$(json_field "$INVOKE_PATH" build_profile)"
skip_smoke="$(json_field "$INVOKE_PATH" skip_smoke)"
artifacts_dir="$(json_field "$INVOKE_PATH" artifacts_dir)"
enable_qemu_smoke="$(toml_field "$CONFIG_PATH" enable_qemu_smoke || printf 'false')"

if [[ ! -r "$REPO_ROOT" ]]; then
  emit_failure "output-permission-denied" "repo_not_readable" "repo root is not readable: $REPO_ROOT"
  exit 1
fi

mkdir -p "$artifacts_dir"

if [[ -x "$EDIT_BIN_BUNDLE" ]]; then
  export YGG_EDIT_BIN="$EDIT_BIN_BUNDLE"
fi

if [[ "$YGG_FORCE_IPV4_DOWNLOADS" == "true" ]]; then
  FORCE_IPV4_BIN_DIR="$(mktemp -d /tmp/ygg-force-ipv4-bin-XXXXXX)"
  cat <<'EOF' > "$FORCE_IPV4_BIN_DIR/wget"
#!/usr/bin/env bash
set -euo pipefail

user_agent=""
output_path=""
urls=()
curl_args=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -O)
      output_path="${2:-}"
      shift 2
      ;;
    -U)
      user_agent="${2:-}"
      shift 2
      ;;
    -nv|--inet4-only)
      shift
      ;;
    --no-check-certificate)
      curl_args+=("--insecure")
      shift
      ;;
    --certificate|--private-key|--ca-certificate)
      shift 2
      ;;
    http://*|https://*|ftp://*)
      urls+=("$1")
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [[ ${#urls[@]} -eq 0 ]]; then
  echo "ygg wget shim: missing URL" >&2
  exit 2
fi

temp_output=""
cleanup_temp() {
  if [[ -n "$temp_output" ]]; then
    rm -f "$temp_output"
  fi
}
trap cleanup_temp EXIT

cmd=(
  /usr/bin/curl
  -4
  -L
  --fail
  --silent
  --show-error
  --retry 8
  --retry-delay 1
  --retry-all-errors
  --connect-timeout 15
  --speed-time 20
  --speed-limit 1024
)
if [[ -n "$user_agent" ]]; then
  cmd+=(-A "$user_agent")
fi
if [[ -n "$output_path" ]]; then
  temp_output="${output_path}.curl-part.$$"
  cmd+=(--output "$temp_output")
fi
last_url_index=$((${#urls[@]} - 1))
cmd+=("${curl_args[@]}" "${urls[$last_url_index]}")
"${cmd[@]}"
if [[ -n "$output_path" ]]; then
  mv -f "$temp_output" "$output_path"
  temp_output=""
fi
EOF
  chmod +x "$FORCE_IPV4_BIN_DIR/wget"
  export PATH="$FORCE_IPV4_BIN_DIR:$PATH"
fi

configure_builder_network
prepare_debootstrap_download_path
patch_debootstrap_for_plain_wget

emit_stage_finished "preflight"
emit_stage_started "build"

rm -rf /workspace/build
mkdir -p "$BUILD_REPO_ROOT"
rsync -a --delete \
  --filter=':- .gitignore' \
  --exclude .git/ \
  --exclude .gstack/ \
  --exclude .agents_chat/ \
  --exclude artifacts/ \
  --exclude binary/ \
  --exclude cache/ \
  --exclude chroot/ \
  --exclude chroot.tmp/ \
  --exclude .build/ \
  --exclude .staging/ \
  --exclude runtime-cache/ \
  --exclude runtime-target/ \
  --exclude target/ \
  --exclude yggdrasil-maker/target/ \
  --exclude '*.iso' \
  --exclude '*.hybrid.iso' \
  --exclude '*.log' \
  "$REPO_ROOT"/ "$BUILD_REPO_ROOT"/
cd "$BUILD_REPO_ROOT"

cmd=(./mkconfig.sh --config "$CONFIG_PATH" --profile "$profile" --skip-smoke)

set +e
"${cmd[@]}" \
  > >(while IFS= read -r line; do emit_log_line "stdout" "$line"; done) \
  2> >(while IFS= read -r line; do emit_log_line "stderr" "$line"; done)
build_status=$?
set -e

if [[ "$build_status" -ne 0 ]]; then
  emit_failure "build-process-failed" "mkconfig_failed" "mkconfig.sh failed for profile $profile"
  exit 1
fi

emit_stage_finished "build"
if [[ "$skip_smoke" != "true" ]]; then
  emit_stage_started "smoke"
  smoke_cmd=(
    ./tests/smoke/run.sh
    --profile "$profile"
    --require-artifacts
    --with-iso-rootfs
    --artifacts-dir ./artifacts
    --server-iso ./artifacts/server-latest.iso
    --kde-iso ./artifacts/kde-latest.iso
  )
  if [[ "$enable_qemu_smoke" == "true" ]]; then
    smoke_cmd+=(--with-qemu-boot)
  fi

  set +e
  "${smoke_cmd[@]}" \
    > >(while IFS= read -r line; do emit_log_line "stdout" "$line"; done) \
    2> >(while IFS= read -r line; do emit_log_line "stderr" "$line"; done)
  smoke_status=$?
  set -e
  if [[ "$smoke_status" -ne 0 ]]; then
    emit_failure "smoke-test-failed" "smoke_failed" "post-build smoke tests failed for profile $profile"
    exit 1
  fi
  emit_stage_finished "smoke"
fi

emit_stage_started "artifact_copy"

copy_if_present() {
  local source="$1"
  local target="$2"
  local profile_name="$3"
  if [[ -f "$source" ]]; then
    cp -f "$source" "$target"
    emit_artifact_ready "$profile_name" "$target"
  fi
}

case "$profile" in
  both)
    copy_if_present "./artifacts/server-latest.iso" "$artifacts_dir/server-latest.iso" "server"
    copy_if_present "./artifacts/kde-latest.iso" "$artifacts_dir/kde-latest.iso" "kde"
    ;;
  server)
    copy_if_present "./artifacts/server-latest.iso" "$artifacts_dir/server-latest.iso" "server"
    ;;
  kde)
    copy_if_present "./artifacts/kde-latest.iso" "$artifacts_dir/kde-latest.iso" "kde"
    ;;
esac

python3 - "$artifacts_dir" "$profile" "$(json_field "$INVOKE_PATH" app_version)" "$(json_field "$INVOKE_PATH" setup_name)" "$(json_field "$INVOKE_PATH" source_mode)" <<'PY'
import hashlib
import json
import pathlib
import sys

artifacts_dir = pathlib.Path(sys.argv[1])
build_profile = sys.argv[2]
app_version = sys.argv[3]
setup_name = sys.argv[4]
source_mode = sys.argv[5]

records = []
for profile_name, file_name in [("server", "server-latest.iso"), ("kde", "kde-latest.iso")]:
    path = artifacts_dir / file_name
    if not path.exists():
        continue
    records.append({
        "kind": "iso",
        "profile": profile_name,
        "path": str(path),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "size_bytes": path.stat().st_size,
    })

payload = {
    "app_version": app_version,
    "setup_name": setup_name,
    "build_profile": build_profile,
    "mode": "local-docker",
    "source_mode": source_mode,
    "artifacts": records,
}
(artifacts_dir / "artifact-manifest.json").write_text(
    json.dumps(payload, indent=2) + "\n",
    encoding="utf-8",
)
PY

emit_stage_finished "artifact_copy"
emit_stage_started "complete"
emit_stage_finished "complete"
