#!/usr/bin/env bash
set -euo pipefail

OUT_FILE="${1:-./yggdrasil.env}"
OUT_DIR="$(dirname "$OUT_FILE")"
mkdir -p "$OUT_DIR"

UI="${YGG_TUI_MODE:-}"
if [[ -z "$UI" ]]; then
  if [[ -t 0 && -t 1 && -n "${TERM:-}" ]]; then
    if command -v whiptail >/dev/null 2>&1; then
      UI="whiptail"
    elif command -v dialog >/dev/null 2>&1; then
      UI="dialog"
    else
      UI="cli"
    fi
  else
    UI="cli"
  fi
fi

choose_cli() {
  local prompt="$1"
  shift
  local options=("$@")
  local i
  echo "$prompt" >&2
  for i in "${!options[@]}"; do
    printf "  %d) %s\n" $((i + 1)) "${options[$i]}" >&2
  done
  while true; do
    printf "Select [1-%d]: " "${#options[@]}" >&2
    read -r pick
    if [[ "$pick" =~ ^[0-9]+$ ]] && (( pick >= 1 && pick <= ${#options[@]} )); then
      echo "${options[$((pick - 1))]}"
      return 0
    fi
    echo "Invalid selection." >&2
  done
}

menu() {
  local title="$1"
  shift
  if [[ "$UI" == "whiptail" ]]; then
    whiptail --title "$title" --menu "Choose:" 20 88 10 "$@" 3>&1 1>&2 2>&3
  elif [[ "$UI" == "dialog" ]]; then
    dialog --clear --title "$title" --menu "Choose:" 20 88 10 "$@" 2>&1 >/dev/tty
  else
    local tags=()
    while [[ $# -gt 0 ]]; do
      tags+=("$1")
      shift 2
    done
    choose_cli "$title" "${tags[@]}"
  fi
}

input() {
  local title="$1"
  local prompt="$2"
  local initial="${3:-}"
  if [[ "$UI" == "whiptail" ]]; then
    whiptail --title "$title" --inputbox "$prompt" 12 88 "$initial" 3>&1 1>&2 2>&3
  elif [[ "$UI" == "dialog" ]]; then
    dialog --clear --title "$title" --inputbox "$prompt" 12 88 "$initial" 2>&1 >/dev/tty
  else
    local val
    printf "%s\n%s\n" "$title" "$prompt" >&2
    printf "Value [%s]: " "$initial" >&2
    read -r val
    echo "${val:-$initial}"
  fi
}

msg() {
  local title="$1"
  local text="$2"
  if [[ "$UI" == "whiptail" ]]; then
    whiptail --title "$title" --msgbox "$text" 14 88
  elif [[ "$UI" == "dialog" ]]; then
    dialog --clear --title "$title" --msgbox "$text" 14 88
  else
    printf "%s\n%s\n\n" "$title" "$text" >&2
  fi
}

setup_mode=$(menu "Setup Mode" \
  recommended "Secure defaults with SSH key embedding" \
  quick-try "Try fast with minimal required fields")

build_profile=$(menu "Build Profile" \
  both "Build both server and KDE" \
  server "Build server ISO only" \
  kde "Build KDE ISO only")

embed_ssh_keys="false"
ssh_keys_file=""
if [[ "$setup_mode" == "recommended" ]]; then
  embed_ssh_keys="true"
  ssh_keys_file=$(input "SSH Keys" "Path to authorized_keys file:" "/root/.ssh/authorized_keys")
  if [[ ! -f "$ssh_keys_file" ]]; then
    msg "Missing file" "SSH key file not found: $ssh_keys_file\nContinuing without embedding keys."
    embed_ssh_keys="false"
    ssh_keys_file=""
  fi
else
  msg "Reminder" "quick-try mode is not recommended for production."
fi

hostname_override=$(input "Hostname" "Live hostname:" "yggdrasil")
lxc_parent_if=$(input "LXC Parent Iface" "Parent interface for LXC macvlan:" "eno1")
macvlan_cidr=$(input "Macvlan CIDR" "Host macvlan CIDR for LXC reachability:" "10.10.0.250/24")
macvlan_route=$(input "Macvlan Route" "Route CIDR for guest subnet:" "10.10.0.0/24")
zpool_name=$(input "ZFS Pool" "ZFS pool name to import at boot:" "zroot")

apt_http_proxy=$(input "APT HTTP Proxy" "Optional (blank if none):" "")
apt_https_proxy=$(input "APT HTTPS Proxy" "Optional (blank = same as HTTP):" "")
apt_proxy_bypass_host=$(input "Proxy Bypass Host" "Optional hostname for DIRECT (blank if none):" "")

cat > "$OUT_FILE" <<EOC
# Generated by scripts/mkconfig-tui.sh
YGG_SETUP_MODE="$setup_mode"
YGG_BUILD_PROFILE="$build_profile"
YGG_EMBED_SSH_KEYS="$embed_ssh_keys"
YGG_SSH_AUTHORIZED_KEYS_FILE="$ssh_keys_file"
YGG_HOSTNAME="$hostname_override"
YGG_LXC_PARENT_IF="$lxc_parent_if"
YGG_MACVLAN_CIDR="$macvlan_cidr"
YGG_MACVLAN_ROUTE="$macvlan_route"
YGG_ZPOOL_NAME="$zpool_name"
YGG_APT_HTTP_PROXY="$apt_http_proxy"
YGG_APT_HTTPS_PROXY="$apt_https_proxy"
YGG_APT_PROXY_BYPASS_HOST="$apt_proxy_bypass_host"
EOC

msg "Saved" "Configuration written to:\n$OUT_FILE\n\nBuild usage:\n./mkconfig.sh --config $OUT_FILE --profile \$YGG_BUILD_PROFILE"
echo "Wrote $OUT_FILE"
